#!/bin/bash
touch /etc/crontab.log
crontab -l > cronfile
echo "0 0 * * * \ md5sum1=\"\$(md5sum /etc/crontab | awk '{ print \$1 }')\" && \ md5sum2=\"\$(cat /etc/crontab.log)\" && \ if [ '\$md5sum1' != '\$md5sum2' ] ; then \  md5sum /etc/crontab | awk '{ print \$1 }' > /etc/crontab.log && mail -s '/etc/crontab modifier' root ; fi" » cronfile
crontab cronfile
rm cronfile
